import esbuild from "esbuild";
import process from "node:process";
import builtinModules from "builtin-modules";

const prod = process.argv[2] === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source available at https://github.com/sasan1200/html-effectiveness
*/`;

// Normalize the builtin-modules export (array, or { default: array }) and add
// the `node:`-prefixed variants so node builtins used by the MCP server (http,
// etc.) are treated as external — they exist at runtime in Obsidian's
// Electron/Node environment (this is a desktop-only plugin).
const builtins = Array.isArray(builtinModules) ? builtinModules : (builtinModules.default ?? []);
const nodeBuiltins = [...builtins, ...builtins.map((m) => `node:${m}`)];

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...nodeBuiltins,
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
